add That_Boii to Stackies
AbbeyIT/Stackie-2023-resolution pull request #18
Opened 2023-01-21 15:48 UTC by D-FOG

## Fixes Issue

## Changes proposed

## Screenshots (If any)

## Questions

## Note to reviewers

2023-01-21 16:57 UTC, AbbeyIT requested changes

2023-01-21 16:57 UTC, AbbeyIT commented on STACKIES.md
> +| [That_Boii](https://github.com/D-FOG) | To build my finances and coding skills
Hi @D-FOG you forget one vertical line at the end to close the table. Feel free to edit the file again and commit it.

2023-01-21 21:03 UTC, D-FOG commented on STACKIES.md
> +| [That_Boii](https://github.com/D-FOG) | To build my finances and coding skills
Hello @AbbeyIT I have edited it. I think it's resolved now.

2023-01-22 14:21 UTC, D-FOG reviewed
@AbbeyIT hello, is it okay

2023-01-23 03:26 UTC, AbbeyIT approved these changes

2023-01-23 03:26 UTC, AbbeyIT commented on STACKIES.md
> +| [That_Boii](https://github.com/D-FOG) | To build my finances and coding skills      |
LGTM! Thank you for your contribution. 🎉On to more green squares. 🟩

2023-01-23 03:26 UTC, merged