Retr0.eth
AbbeyIT/Stackie-2023-resolution pull request #22
Opened 2023-01-21 17:00 UTC by Ayan-M-Dev

## Fixes Issue

## Changes proposed

## Screenshots (If any)

## Questions

## Note to reviewers

2023-01-21 17:06 UTC, AbbeyIT requested changes

2023-01-21 17:06 UTC, AbbeyIT commented on STACKIES.md
> +| [Retr0.eth](https://github.com/Ayan-M-Dev)           | To get better as a developer, get an internship & gain weight and become healthy  |
Hi @Ayan-M-Dev Insert you name before Roy. Feel free to edit the file again and push it.

2023-01-22 10:25 UTC, Ayan-M-Dev commented on STACKIES.md
> +| [Retr0.eth](https://github.com/Ayan-M-Dev)           | To get better as a developer, get an internship & gain weight and become healthy  |
Okay done

2023-01-23 03:27 UTC, AbbeyIT approved these changes

2023-01-23 03:27 UTC, AbbeyIT commented on STACKIES.md
> +| [Retr0.eth](https://github.com/Ayan-M-Dev)           | To get better as a developer, get an internship & gain weight and become healthy  |
LGTM! Thank you for your contribution. 🎉On to more green squares. 🟩

2023-01-23 03:28 UTC, merged