add Haykay to Stackies
AbbeyIT/Stackie-2023-resolution pull request #26
Opened 2023-01-21 23:43 UTC by Haykay2020

## Fixes Issue

## Changes proposed

## Screenshots (If any)

## Questions

## Note to reviewers

2023-01-22 02:55 UTC, AbbeyIT requested changes

2023-01-22 02:55 UTC, AbbeyIT commented on STACKIES.md
> +  [itscurious](https://github.com/ShantanuK86)         | To explore more technologies and travel more              |
Hi @Haykay2020 Kindly add some vertical line for line 8 before `itscurious` name. 

I think you accidentally removed it. Feel free to change your file and commit again, No need to closed this PR and open a new one.

2023-01-22 07:15 UTC, Haykay2020 commented on STACKIES.md
> +  [itscurious](https://github.com/ShantanuK86)         | To explore more technologies and travel more              |
I have updated it.

2023-01-23 03:29 UTC, AbbeyIT approved these changes

2023-01-23 03:29 UTC, AbbeyIT commented on STACKIES.md
> +| [haykay](https://github.com/Haykay2020)	       | To become a better software developer and learn a job     |
LGTM! Thank you for your contribution. 🎉On to more green squares. 🟩

2023-01-23 03:30 UTC, merged